#!/usr/bin/env fish

set programs (grep -o '^\s*case \w*$' (status filename) | cut -d' ' -f2)

set program (echo -e $programs | rofi -dmenu -p "edit dotfile for" -sep ' ') 


set CONFIG "$HOME/.config"

switch (echo $program | string trim)
	case nvim
		kitty -e nvim "$CONFIG/nvim/init.vim"
	case fish
		kitty -e nvim "$CONFIG/fish/config.fish"
	case rofi
		kitty -e nvim "$CONFIG/rofi/theme.rasi"
	case polybar
		kitty -e nvim "$CONFIG/polybar/config.ini"
	case i3
		kitty -e nvim "$CONFIG/i3/config"
	case dunst
		kitty -e nvim "$CONFIG/dunst/dunstrc"
	case ranger
		kitty -e nvim "$CONFIG/ranger/rc.conf"
	case picom
		kitty -e nvim "$CONFIG/picom.conf"
	case qutebrowser
		kitty -e nvim "$CONFIG/qutebrowser/config.py"
	case kitty
		echo $CONFIG
		ls $CONFIG/kitty
		kitty -e nvim "$CONFIG/kitty/kitty.conf"
	case '*'
		notify-send "dotfile for $program not found"
end
