#!/usr/bin/env fish
set action (echo "pomodoro (infinite)
pomodoro (finite)
back up...
sync rocketbook
lock
logout
shutdown
reboot
back up all & shutdown
sync clock
upgrade" | rofi -dmenu -p power)

switch $action
	case "pomodoro (infinite)"
		$HOME/pomodoro
	case "pomodoro (finite)"
		$HOME/pomodoro --sessions-of=4 --total-cycles=(rofi -dmenu -p "number of cycles")
	case "back up..."
		set dir (echo "music
ideas
projects
resources" | rofi -dmenu)
		kitty $HOME/$dir/backup
	case "sync rocketbook"
		kitty $HOME/rb/routine
	case "lock"
		betterlockscreen --lock
	case "logout"
		i3-msg exit
	case "shutdown"
		shutdown now
	case "reboot"
		reboot
	case "back up all & shutdown"
		kitty fish -c 'for dir in music ideas projects; $HOME/$dir/backup; end; shutdown'
	case "sync clock"
		kitty fish -c 'sudo ntpd -qg'
	case "upgrade"
		kitty fish -c paru
end

