#!/usr/bin/env fish
set action (echo "pomodoro (infinite)
pomodoro (finite)
back up...
sync rocketbook
lock
logout
shutdown
reboot
back up all & shutdown
sync clock
upgrade" | rofi -dmenu -p power)

switch $action
	case "pomodoro (infinite)"
		$HOME/pomodoro
	case "pomodoro (finite)"
		$HOME/pomodoro --sessions-of=4 --total-cycles=(rofi -dmenu -p "number of cycles")
	case "back up..."
		set dir (echo "music
music (w/ download)
ideas
projects
resources" | rofi -dmenu)
		if test $dir = "music (w/ download)"
			kitty fish -c "$HOME/music/backup && $HOME/music/download.py && $HOME/music/fill-playlists.py && $HOME/music/update-artist-counts.py"
		else
			kitty $HOME/$dir/backup
		end
	case "sync rocketbook"
		kitty $HOME/rb/routine
	case "lock"
		betterlockscreen --lock
	case "logout"
		i3-msg exit
	case "shutdown"
		shutdown now
	case "reboot"
		reboot
	case "back up all & shutdown"
		kitty fish -c '~/do-backups && shutdown now'
	case "sync clock"
		kitty fish -c 'sudo ntpd -qg && sudo hwclock --systohc'
	case "upgrade"
		kitty fish -c yay
end

