#!/usr/bin/env fish
set action (echo "pomodoro
back up...
sync rocketbook
shutdown
reboot
back up all & shutdown
sync clock
upgrade" | rofi -dmenu -p power)

switch $action
	case "pomodoro"
		$HOME/pomodoro
	case "back up..."
		set dir (echo "music
ideas
projects
resources" | rofi -dmenu)
		kitty $HOME/$dir/backup
	case "sync rocketbook"
		kitty $HOME/rb/routine
	case "shutdown"
		shutdown now
	case "reboot"
		reboot
	case "back up all & shutdown"
		kitty fish -c 'for dir in music ideas projects; $HOME/$dir/backup; end; shutdown'
	case "sync clock"
		kitty fish -c 'sudo ntpd -qg'
	case "upgrade"
		kitty fish -c paru
end

