gui:
  showIcons: true
  theme:
    activeBorderColor:
      - '#94e2d5'
      - bold
    inactiveBorderColor:
      - '#a6adc8'
    optionsTextColor:
      - '#89b4fa'
    selectedLineBgColor:
      - '#313244'
    selectedRangeBgColor:
      - '#313244'
    cherryPickedCommitBgColor:
      - '#45475a'
    cherryPickedCommitFgColor:
      - '#94e2d5'
    unstagedChangesColor:
      - '#f38ba8'
    defaultFgColor:
      - '#cdd6f4'
    searchingActiveBorderColor:
      - '#f9e2af'
git:
  overrideGpg: true
  paging:
    colorArg: always
    externalDiffCommand: difft
keybinding:
  commits:
    viewResetOptions: '<c-g>'
customCommands:
  - key: g
    command: gitmoji -c
    context: global
    subprocess: true
  - key: G
    command: close-issue
    context: files
    subprocess: true
  - key: '<c-p>'
    context: files
    prompts:
      - type: input
        title: What's the MR title?
        key: MRTitle
        suggestions:
          command: 'git log --oneline --pretty=format:"%s"'
    subprocess: true
    command: GL_HOST=git.inpt.fr glab mr create --fill --title "{{ .Form.MRTitle }}"
  - key: '<c-p>'
    context: localBranches
    prompts:
      - type: input
        title: What's the MR title?
        key: MRTitle
        suggestions:
          command: 'git log --oneline --pretty=format:"%s" "{{.SelectedLocalBranch}}"'
    subprocess: true
    command: GL_HOST=git.inpt.fr glab mr create --fill --title "{{ .Form.MRTitle }}"
      --target-branch "{{ .SelectedLocalBranch }}"
