gui:
  theme:
    lightTheme: false
  showFileTree: true
git:
  paging:
    colorArg: always
    pager: delta --paging=never
customCommands:
  - key: g
    context: files
    command: gitmoji -c
    description: commit with gitmoji
    subprocess: true
