gui:
  theme:
    lightTheme: false
  showFileTree: true
git:
  paging:
    colorArg: always
    pager: delta --paging=never
customCommands:
  - key: g
    context: files
    command: gh il; gitmoji -c
    description: commit with gitmoji
    subprocess: true
  - key: I
    context: files
    command: gh issue list
    description: see open github issues
    subprocess: true
  - key: 'N'
    description: create annotated tag
    command: git tag -a {{index .PromptResponses 0}} -m "{{index .PromptResponses
      1}}"
    context: tags
    prompts:
      - type: input
        title: Annotated tag name
      - type: input
        title: Annotated tag message
