gui:
  showIcons: true
  theme:
    activeBorderColor:
      - '#94e2d5'
      - bold
    inactiveBorderColor:
      - '#a6adc8'
    optionsTextColor:
      - '#89b4fa'
    selectedLineBgColor:
      - '#313244'
    selectedRangeBgColor:
      - '#313244'
    cherryPickedCommitBgColor:
      - '#45475a'
    cherryPickedCommitFgColor:
      - '#94e2d5'
    unstagedChangesColor:
      - '#f38ba8'
    defaultFgColor:
      - '#cdd6f4'
    searchingActiveBorderColor:
      - '#f9e2af'
git:
  paging:
    useConfig: true
keybinding:
  commits:
    viewResetOptions: '<c-g>'
customCommands:
  - key: g
    command: gitmoji -c
    context: global
    subprocess: true
